### ISSUE TITLE
Fail uploadBinaries: do you have any idea why? Thanks :pray: !

### ISSUE THREAD

**Issue by Naereen** [Adrilaw/OdinV4#2]
Hi there,
I used your `odin4` tool on a Ubuntu 22.04 laptop, for a Samsung Galaxy A20e.
- [x] The device is correctly found (`$ odin4 -l` gives `/dev/bus/usb/001/103` for instance).
- [ ] Running a `/odin4 -b BL*.tar.md5 -a AP*.tar.md5 -c CP_*tar.md5 -s HOME_CSC_*tar.md5` command gives me this message and then fails:
```bash
Check file : BL_A202FXXU2ASG1_CL16308935_QB24741298_REV00_user_low_ship.tar.md5
Check file : AP_A202FXXU2ASG1_CL16308935_QB24741298_REV00_user_low_ship_meta_OS9.tar.md5
Check file : CP_A202FXXU2ASF3_CP13132746_CL16308935_QB24514907_REV00_user_low_ship.tar.md5
Check file : HOME_CSC_OMC_OXM_A202FOXM2ASG1_CL16308935_QB24741298_REV00_user_low_ship.tar.md5
meta-data/download-list.txt
/dev/bus/usb/001/103
/dev/bus/usb/001/103
Setup Connection
initializeConnection
Receive PIT Info
success getpit
Upload Binaries
sboot.bin.lz4
cm.bin.lz4
Fail request receive -1
FAIL!
Fail uploadBinaries
```
Do you have any idea why? Is there something I didn't do correctly?
Thanks in advance! Regards from France :smiley: !
@Naereen

**Comment by Naereen** [comment]
Note: I followed the tutorial explained here <https://android.stackexchange.com/a/257436>

**Comment by Adrilaw** [comment]
Hello please feel free to talk to me on telegram +23058307432

**Comment by Naereen** [comment]
Yeah, I don't think so. Development happen here on GitHub or it does not happen, sorry.
Thanks for replying anyway :smile: !

**Comment by Adrilaw** [comment]
> Yeah, I don't think so. Development happen here on GitHub or it does not happen, sorry. Thanks for replying anyway 😄 !

./odin4 -b BL*.tar.md5 -a AP*.tar.md5 -c CP_*tar.md5 -s HOME_CSC_*tar.md5 try sudo ./odin or sudo odin
